R/setters.R, tests/testthat/test-SPC-objects.R
Here are some proposed changes to the `horizons()` setter that will auto-merge in new values, provided the input dataframe has the same profile_id/idname and hzID/hzidname.
Addresses #82 
So far, this passes tests and doesn't appear to nuke any preexisting functionality. I may have missed something, though, so I've created this branch for testing.
Install branch for testing:
```
devtools::install_github('ncss-tech/aqp@hzset', dependencies=FALSE, build=FALSE, upgrade=FALSE)
```
Example usage/tests:
```
library(aqp)
library(testthat)
data(sp1, package = 'aqp')
depths(sp1) <- id ~ top + bottom
site(sp1) <- ~ group
x <- sp1
hnew <- horizons(x)[, c(idname(x), hzidname(x), 'prop')]
hnew$prop100 <- hnew$prop / 100
hnew$prop200 <- hnew$prop / 200
hnew$prop300 <- hnew$prop / 300
hnew$prop[1] <- 50 …
```
=> add merge capability to horizons() setter for SPC objects.

NAMESPACE, NEWS.md, R/colorQuantiles.R, R/evalGenHz.R, R/get.ml.hz.R, R/slab.R, R/soilColorSignature.R, man/SPC-slab-methods.Rd
Related to #79 and #157. Note that this PR modifies NAMESPACE.
=> Replace {reshape} melt and cast with {data.table} methods.

R/checkHzDepthLogic.R, man/checkHzDepthLogic.Rd, misc/sandbox/checkHzDepthLogic-byhz.R, tests/testthat/test-checkHzDepthLogic.R
This is a minimal-changes-to-existing-interface demonstration of running `hzDepthTests` by horizon with `checkHzDepthLogic(byhz=TRUE)` based on the suggestions from @smroecker and highlighted in #197.
This may not completely address full needs/output format of the logic-checking portion of Stephen's suggestion, but may provide a skeleton and format for extension of existing functionality to better horizon level check output.
My demo at end of this code block shows how the `overlapOrGap` error does not make sense in the "by horizon" context. We could omit it, or write an alternate form of hzDepthTests that is specific to single-horizon evaluations.
```r
library(aqp)
data("jacobs2000")
checkHzDepthLogic(jacobs2000)
#>     id valid depthLogic sameDepth missingDepth overlapOrGap
#> 1 92-1 …
```
=> demo of checkHzDepthLogic(byhz=TRUE)

R/SoilProfileCollection-operators.R, man/singlebracket.Rd, misc/aqp2/jindex-benchmarks.R, misc/aqp2/test-k-keywords.R, tests/testthat/test-SPC-k-keywords.R
This was inspired by discussion on #199, a continuation of the efforts in #157 and of prior optimizations of SPC operators, and customizations for data.table SPCs in #155. This PR is extending the benefits for all SPC data.frame subclasses.
EDIT:
EDIT2:
Agreeing with Dylan below. I reverted this to draft for now. 
Some more explanation. Before this PR, data.table SPC j-index should only be invoked if the `aqp_df_class` of the object is `"data.table"`. This PR removes one of the few code "forks" between data.table and base in favor of a data.table. 
We could more formally "archive" base R equivalent code using in tests where things should be expected to be the same. For now, I left mine commented, and several new realizations of the base code in this PR worth trying out.
In some way I see …
=> data.table optimization of SPC j-index and adding k-keywords

R/SoilProfileCollection-methods.R
Following from #207 (updates to `fillHzGaps`). This gap-fill method now supports filling to the surface and filling to depth. The default fill-to depths are `0` for the `to_top` argument and `max(SPC)`  isdefault `to_bottom`.
`min` and `max` have benefitted from the "k-keyword" `.LAST` which was introduced in #201 and discussed at end of #175
=> use .LAST k-keyword in min(SPC)/max(SPC)

R/glom.R, R/glomApply.R, man/glom-SoilProfileCollection-method.Rd, tests/testthat/test-dplyr-verbs.R, tests/testthat/test-glom.R
This vectorizes `glom`-- "glomming clods" is no longer limited to single profile SoilProfileCollections
- Many warnings and checks have been eliminated; this change is aided by the fact that many new developments have been made for checking and fixing depth logic errors
- `trunc,SoilProfileCollection-method` gets a  _very_ significant speed boost from this. Several hundred times faster with larger n >10000 collections.
- Limited new tests of the _vectorized_ functionality with existing single-profile tests essentially unchanged
=> glom: vectorized over profiles!

R/Class-SoilProfileCollection.R, R/SoilProfileCollection-spatial.R, misc/sandbox/findNormalizableVars.R, tests/testthat/test-DT-tbl.R
Thanks @jacobisleib, CT Resource Soil Scientist and one of our ncss-tech aqp users for bringing me an interesting example.
If building an SPC with custom data.frame we start with horizon-level data which we pass to `depths<-` 
We need to ["normalize"](https://en.wikipedia.org/wiki/Denormalization) coordinates with `site(spc) <- ~ formula` before we can use `coordinates(spc) <- ~ formula`. I figure this process of promoting to _SoilProfileCollection_ can be streamlined. 
Common errors relate to misspelled or missing column names. But a case we can handle more intelligently is when the right data are present in `@horizons` but not yet normalized to `@site`. 
``` r
library(aqp, warn=FALSE)
#> This is aqp 1.29
library(data.table)
n <- 10
randomsite <- data.table(
id = 1:n,
x = runif(n),
y = …
```
=> Have coordinates<- look for horizon "denormalized" XY before error

R/SoilProfileCollection-setters.R
Small "fix" or at least drawing attention something I noticed. Comes up if user doesn't check for more than 1 row of data before using `depths<-`.
When a valid formula/column names are given to `depths<-`, but the data result in an empty SPC being produced (e.g. empty data.frame) return a SPC with the slots that the user specified, not the default values stored in `SoilProfileCollection()` constructor (id/top/bottom). 
``` r
library(aqp)
#> This is aqp 1.29
h <- data.frame(pid=1:3, hzdept=rep(0:3,3), hzdepb=rep(1:4,3))
h2 <- h[0,]
depths(h) <- pid ~ hzdept + hzdepb
#> converting profile IDs from integer to character
h
#> SoilProfileCollection with 3 profiles and 12 horizons
#> profile ID: pid  |  horizon ID: hzID 
#> Depth range: 4 - 4 cm
#> 
#> ----- Horizons (6 / 12 rows  |  4 / 4 …
```
=> .initSPCfromMF: return 0-length SPC with idcol/hzdepthcols

DESCRIPTION, NAMESPACE, NEWS.md, R/munsell2rgb.R, R/soilColorIndices.R, man/harden.rubification.Rd, man/parseMunsell.Rd, tests/testthat/test-color-conversion.R
This PR implements an improved `parseMunsell`, which now can handle less stable munsell notations, eg using other delimiters than `/`, or missing white spaces.
One study case remains to be implemented: `x.neutral <- parseMunsell('N 2/')`, but it should be possible to adapt this code, which essentially splits the munsell string into 3 parts.
=> Improved `parseMunsell`

R/glom.R, R/mollicEpipedon.R, man/glom-SoilProfileCollection-method.Rd, tests/testthat/test-mollic.R
This PR patches a bug that produced an unintended `replaceHorizons<-` error `"profile IDs in replacement are missing from site!"`. This was introduced when `glom` was updated to be vectorized, but I think only affects the single-profile case.
The problem identified in the heuristics for finding cambic horizons and removal of overlapping layers that are identified as part of an argillic. Typically occurred when the result of `glom(..., invert=TRUE)`  only had one part above or below the (inverted) glom interval corresponding to the argillic horizon boundaries.
=> glom/mollic.thickness.requirement handle NA index case for `invert=TRUE`

misc/sandbox/fixOhorizons.R
Sandbox example for calculating new horizon depths for profiles that have the "old style" horizon depths.
This was developed in collaboration with @jskovlin for working with USFS pedons import into NASIS from their point data repository.
=> Basic routine for accumulating horizon depths to fix old O horizons etc

R/estimateAWC.R, tests/testthat/test-awc.R
- Uses `data.frame(stringsAsFactors=FALSE)` and a label column instead of `dput()` structure containing a factor column.
=> Fix estimateAWC errors on R 3.6.x

NEWS.md, R/SoilProfileCollection-methods.R, R/depthOf.R, R/getSurfaceHorizonDepth.R, R/glom.R, man/depthOf.Rd, man/getSurfaceHorizonDepth.Rd, man/glom-SoilProfileCollection-method.Rd, misc/aqp2/glomDepthOfDemo.R, misc/aqp2/multiglomDT.R, tests/testthat/test-genhz.R, tests/testthat/test-glom.R, tests/testthat/test-mollic.R, tests/testthat/test-soil-depth.R, tests/testthat/test-surface-thickness.R
- Vectorizes `glom()` `z1` and `z2` arguments, so now profile-specific intervals may be specified. `z1` and `z2` must be either length 1 or length equal to number of profiles. `z2` may be `NULL` for "point"-horizon intersection. 
- `z1` and `z2` now support non-standard evaluation of expressions based on column names in `siteNames(p)`, and also can evaluate character vectors (length 1) that are column names in `siteNames(p)`. This makes new vectorized version even easier to use in pipe-based workflows
- `depthOf` can now be applied to multiple profiles. If length(SPC) > 1 returns a _data.frame_ result containing ID, depth, designation and pattern
- `minDepthOf` and `maxDepthOf` use a shared functional form, which can also be called via optional `FUN` argument to `depthOf`
- …
=> Vectorize `glom`, `depthOf`, `getSurfaceHorizonDepth`

NAMESPACE, R/SoilProfileCollection-methods.R, man/subset-SoilProfileCollection-method.Rd
This PR removes the deprecated `aqp::filter()` command. 
As replacement, there is a `subset()` method defined for the SoilProfileCollection S4 object that does not cause conflicts with base or dplyr usage of functions of the same name. You can pass logical expressions to that function in the same way you would `base::subset()` or `dplyr::filter()`.
=> Remove aqp::filter

R/Class-SoilProfileCollection.R, man/show.Rd
Currently, you can store a list of SoilProfileCollection as a column of a data.frame when protected with `I()`. This could be pretty convenient if you have multiple groups of pedons that you need to manage.
But if you try to print that data frame in the console, you will get an error because there is no way to represent the list of SPC as a character vector. 
If we were to define the S4 method `as.character()` for the SoilProfileCollection this would be resolved. 
This PR provides an example of how it could be defined; formatting could be changed as needed.
``` r
library(aqp, warn.conflicts = FALSE)
#> This is aqp 1.31
data(sp1)
depths(sp1) <- id ~ top + bottom
data(sp2)
depths(sp2) <- id ~ top + bottom
test <- data.frame(id = 1:2, foo = I(list(sp1, sp2)))
test
#> Error in …
```
=> Add `as.character(<SoilProfileCollection>)`

R/repairMissingHzDepths.R, man/repairMissingHzDepths.Rd, tests/testthat/test-repairMissingHzDepths.R
This PR applies the new function `spc_horizonOffset()`  to extend the repairMissingHzDepths() function
=> repairMissingHzDepths: Use `spc_horizonOffset()`

R/SoilProfileCollection-methods.R, R/SoilProfileCollection-setters.R, man/depths.Rd, tests/testthat/test-SoilProfileCollection-setters.R
This is an extension of a prior update involving 0-length SPCs and horizon data where all depths are NA: https://github.com/ncss-tech/aqp/pull/218. This is possibly related to #214 
This PR is to allow for column names from a source (possibly empty) site or horizon data.frame to be included in the "prototype" SPC created by `.prototypeSPC()`. Previously only the required column names were filled in, allowing for idname/depthcols customization and returning a valid 0-length SPC, but dropping other columns that may have been present in the horizon data being promoted to SPC.
My main interest is to ensure that after construction a prototype SPC has the same names as another SPC that was created from more complete horizon data.
``` r
library(aqp)
#> This is aqp 1.33
x <- data.frame(id = …
```
=> Empty SPC prototype should be able to preserve horizon names

R/slab.R
- adjusts for changes in R 4.2.x; `aggregate.formula()` now follows generic `aggregate(x, ...)` https://bugs.r-project.org/show_bug.cgi?id=18299
- when passing a (named) list of arguments to `aggregate()` via `do.call()` need to _not_ specify argument name (which is `formula` R < 4.2, and `x` on R >= 4.2)
- It is implied that `aggregate.formula()` will be called when first argument is class formula
=> `slab()`: pass `formula` argument to aggregate.formula(x, ...)

R/plotSPC.R
Adds `.interpretHorizonColor()` outputs to `last_spc_plot` in `aqp.env` for use in custom `legend()`.
For example:
<details>
``` r
library(aqp)
#> This is aqp 1.43
library(soilDB)
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 8.2.1; sf_use_s2() is TRUE
library(sharpshootR)
bb1 <- '-101.4810 38.0560,-101.4810 38.0620,-101.4675 38.0620,-101.4675 38.0560,-101.4810 38.0560'
bb2 <- '-101.1952 37.8600,-101.1952 37.8843,-101.1410 37.8843,-101.1410 37.8600,-101.1952 37.8600'
x1 <- st_as_sfc(sprintf('POLYGON((%s))', bb1), crs = 4326)
x2 <- st_as_sfc(sprintf('POLYGON((%s))', bb2), crs = 4326)
m1 <- SDA_spatialQuery(x1, what = 'mukey')
m2 <- SDA_spatialQuery(x2, what = 'mukey')
s1 <- get_component_from_SDA(
sprintf(
"mukey IN %s AND majcompflag = 'Yes' AND compkind != 'Miscellaneous …
```
=> Add `.interpretHorizonColor()` outputs to `last_spc_plot` 

R/SoilProfileCollection-iterators.R, man/profileApply.Rd
Adds support for custom `lapply()`-like function (`APPLY.FUN`) for processing chunks in `profileApply()`
- e.g. `future.apply::future_lapply()` for processing chunks in parallel
``` r
library(aqp)
#> This is aqp 1.43
library(future.apply)
#> Loading required package: future
plan(multisession) ## Run in parallel on local computer
set.seed(123)
spc <- data.table::rbindlist(lapply(1:10000, random_profile, SPC=FALSE))
depths(spc) <- id ~ top + bottom
system.time({
x1 <- profileApply(spc, function(p) {
thickness = ifelse(is.na(p$p1), 0, p$bottom - p$top)
p$p1avg = sum((thickness) * p$p1 / sum(thickness), na.rm = TRUE)
p$p1avg
})
})
#>    user  system elapsed 
#>   25.25    0.01   25.31
system.time({
x2 <- profileApply(spc, function(p) {
thickness = ifelse(is.na(p$p1), 0, p$bottom - p$top) …
```
=> `profileApply`: Add support for custom `lapply()`-like function for processing chunks

R/mixMunsell.R, R/sketch-utils.R, tests/testthat/test-DT-tbl.R, tests/testthat/test-NCSP.R, tests/testthat/test-SPC-combine.R, tests/testthat/test-aqp.R, tests/testthat/test-color-conversion.R, tests/testthat/test-mixMunsell.R, tests/testthat/test-plotSPC.R, tests/testthat/test-profile_compare.R, tests/testthat/test-slab.R
Some notes/fixes from testing on a fresh machine with a minimal set of dependencies.
- removes {scales} dependency from `plotSPC()`
- removes {plyr} usage from test-SPC-combine.R
- <strike>skip `mixMunsell()` tests if {gower} not installed</strike>
fixed bad logic that required {gower} for `mixMunsell(..., mixingMethod="exact")`
- avoid usage of `aqp:::` in tests
- skip `profile_compare()` (deprecated) tests if {scales} is not installed
- skip some `slab()` tests if {Hmisc} is not installed
=> Fixing tests and issues with minimal install

R/split.R, man/split-SoilProfileCollection-method.Rd, tests/testthat/test-split.R
`split()` allows `NA` levels (and preserves them as `"<missing>"` when `drop=FALSE`)
``` r
library(aqp)
#> This is aqp 2.0
data("jacobs2000")
site(jacobs2000)$grp1 <- c(1, 1, 1, 2, 2, NA, NA)
site(jacobs2000)$grp2 <- c(1, 2, 1, 2, 1, 2, 1)
x <- split(jacobs2000, jacobs2000$grp1)
length(x)
#> [1] 2
x <- split(jacobs2000, "grp1", drop = FALSE)
#> converting grp1 to factor
length(x)
#> [1] 3
length(x[["<missing>"]])
#> [1] 2
x <- split(jacobs2000, list(jacobs2000$grp1, jacobs2000$grp2))
length(x)
#> [1] 4
x <- split(jacobs2000, list(jacobs2000$grp1, jacobs2000$grp2), drop = FALSE)
length(x)
#> [1] 6
names(x)
#> [1] "<missing>.1" "1.1"         "2.1"         "<missing>.2" "1.2"        
#> [6] "2.2"
jacobs2000$grp3 <- factor(jacobs2000$grp2, levels = 1:10)
x <- split(jacobs2000, …
```
=> `split()`: allow `NA`->`"<missing>"` levels

R/slab-utils.R, R/slab.R, man/slab.Rd, tests/testthat/test-slab.R
@dylanbeaudette found a couple issues with dontrun examples in `slab()` that I have made some preliminary corrections for.
Issue 1: related to the data type of an all NA column being logical rather than double -- corrected by using `as.numeric()` in `.slab.fun.numeric.HD()`
Issue 2: related to a case we didn't have tests for and apparently had not been checked/identified as a problem since the `slab()` rewrite 
-  `.genSlabLabels2()` has been corrected to adjust for minimum slice depth within a slab. Previously was returning all NA labels in cases where `slab.structure[1] > 0`. Added a new test for this case. 
Also small correction to `slab()` example for recent update to `get.ml.hz()` in https://github.com/ncss-tech/aqp/commit/a8932cfed95caedc0f418c56a43e0747b4632fcc
=> Fix examples for `slab()`

DESCRIPTION, R/flagOverlappingHz.R, man/flagOverlappingHz.Rd, tests/testthat/test-flagOverlappingHz.R
`flagOverlappingHz()` is called by `fillHzGaps()` which is used by several higher level functions including:
- `dice()` / `slab()` 
- `profileInformationIndex()`
- `spc2mpspline()`
The current implementation of `flagOverlappingHz()` on master branch is slow, based on iteration over single profile SPCs, and complex operations on each element... it is the major bottleneck in `fillHzGaps()`.
This PR improves processing time by approximately 4 orders of magnitude with a 10,000 profile SoilProfileCollection. It also allows for flagging overlap in horizons that have missing depths (a TODO item), improves tests, and ensures that _imperfectly_ overlapping horizons are not flagged.
```r
library(aqp)
#> This is aqp 2.0.3
x <- data.table::rbindlist(lapply(1:10000, random_profile, SPC = FALSE)) …
```
=> `flagOverlappingHz()` performance improvements

R/Class-SoilProfileCollection.R, R/SoilProfileCollection-integrity.R, R/SoilProfileCollection-metadata.R, tests/testthat/test-SPC-objects.R
This was only used for `reorderHorizons()` default functionality. It is rare that this function is used, nor that we don't know the desired target order. `reorderHorizons()` now requires `target.order` be specified 
Metadata with a numeric vector of the order of input data was set for every SPC (which could be a bit costly in terms of time/memory for large SPCs) but only was used for `reorderHorizons()` which is rarely needed or used.
This metadata entry, and the formerly present `target.order` metadata, were held over from my ideas on how to implement alternate profile sorting methods (i.e. not dependent on alpha sorting of profile ID + top depth). We decided to not change the historic sorting behavior.
I think that the better way to implement numeric/alternate profile sorting in the …
=> Remove `"original.order"` from SPC metadata

R/generalize.hz.R, man/generalize.hz.Rd
This PR addresses behavior of `generalize.hz()` when `hzdepm` contains `NA`. It adds `na.rm` argument for finer-tuned handling of missing depths. This argument affects both the handling of `NA` values by `median()` and the `sort()` behavior for a cases where median is `NA`
``` r
library(aqp)
#> This is aqp 2.1.0
data(sp4)
depths(sp4) <- id ~ top + bottom
hzdesgnname(sp4) <- "name"
sp4_1 <- generalizeHz(sp4, c("A", "Bt"), c("A", "Bt"), hzdepm = apply(depths(sp4)[2:3], 1, mean))
generalize.hz(sp4$name, c("A", "Bt"), c("A", "Bt"), hzdepm = apply(depths(sp4)[2:3], 1, mean))
#>  [1] A  Bt Bt Bt A  Bt A  Bt Bt A  Bt Bt Bt A  Bt Bt A  Bt A  Bt A  Bt A  A  A 
#> [26] Bt Bt A  Bt Bt
#> Levels: A < Bt < not-used
table(sp4_1$genhz)
#> 
#>        A       Bt not-used 
#>       12       18        0 …
```
=> `generalize.hz(hzdepm = ...)`: more robust sorting in presence of missing depths
